version: '3.8'
services:
  mcp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000" # ホストの3000番ポートをコンテナの3000番ポートにマッピング
    environment:
      # 環境変数をここで設定 (例: MinecraftサーバーのIP、ポート)
      MINECRAFT_SERVER_HOST: "your_minecraft_server_ip"
      MINECRAFT_SERVER_PORT: "25565"
      MCP_SERVER_PORT: "3000"
    restart: always # コンテナが終了した場合に自動的に再起動
